language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- npm run build
- npm run test
- npm run cover
env:
  global:
    secure: Qbb8F/G4voGA4Z1fQA2ZGGv2nyxhSBpASQJQWs2Se2+7trgYKc3pHEjFT69E0IXKvDOLaO6eYXzOxTi92+VMO/L5A9AOn+lqDBB01D2xIchD6PWhkdhHkHn/39hdotIyQs4RaogQ6KiiNvgrkLJSQQb51fdmgxtPz6xCniT1q1SZluE9XXZO89gIzHtnZBQd8Wuyq2m4AwGcCgwNws5ctxxrR8fFI9qVeVAY15OMJBunRH+eUKR0oCWUcGjGKN6e10SP0pSEi7twgMVL/GhrCzgmh+KI82bfYb+wq+CvvDJrCz0TOMpaBFVfml4fAgYRNqvjnH6iSVx26tW7mvJoKyzQm24hYwbzfYn3F9d+rlQ+W0J9WVrToXIGUoN0Dkzc8yV0MtDfkQEIs7GeAr5532NJZEdSDyPtMzvsaV0U+MWyT8TW5yr6edk7j86nbu9F98huRNlLXQbkj+UBx0a+R38jW/87FGj95/ITGlrFUKAZbhvLKcfMtpYVMdAi8XQFwcAdMTUpCZidgXheg5elQg5LisGLvDeED2Xuy5iYL6DJ84ipLowdmg2ZmsKK3afIIRaVAiZaKCtadwpL5bNeBCBHdgIIEWAPftvyAT9OOWuM9gw8zhFLLhalYmk38rg/1MLuTIevL/pUYatbh6LHuwnXOY0ym9+udnIxzaAN/iY=
